settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-validate-example/go
  path: .
  commands:
    install:
      status: true
      method: go build -o main
    run:
      status: true
      method: ./main
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
- name: go-validate-example/proto
  path: .
  watcher:
    extensions:
    - proto
    paths:
    - .
    ignored_paths:
    - .git
    - .realize
    scripts:
    - type: before
      command: bash ./gen-pb.sh
      output: true
